version: '3.8'

services:
  api:
    build: .
    container_name: glucose-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////data/glucose.db
    volumes:
      - glucose-data:/data
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped

volumes:
  glucose-data:
    driver: local